# Generated by Django 4.0.4 on 2023-06-07 11:40

from django.db import migrations, models
import django.db.models.deletion
import printPreview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachements_Type',
            fields=[
                ('ATTACHMENT_TYPE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('DESCRIPTION', models.TextField()),
            ],
            options={
                'db_table': 'ATTACHMENT_TYPES',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tools_country',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('REQUEST_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('REQUEST_NO', models.TextField()),
                ('REQUEST_START_DATE', models.TextField()),
                ('FACILITY_NUMBER', models.DateField()),
                ('FACILITY_NAME', models.TextField()),
                ('GOVERNORATE_CODE', models.TextField()),
                ('GOVERNORATE_NAME', models.TextField()),
                ('CITY_CODE', models.TextField()),
                ('CITY_NAME', models.TextField()),
                ('INDUSTRIAL_ZONE_CODE', models.TextField()),
                ('INDUSTRIAL_ZONE_NAME', models.TextField()),
                ('DETAILED_ADDRESS', models.TextField()),
                ('INVESTOR_ID', models.TextField()),
                ('COMMN_NAME', models.TextField()),
                ('OWNER_NAME', models.TextField()),
                ('CREATION_DATE', models.TextField()),
                ('CREATED_BY', models.TextField()),
                ('REQUESTER_PHONE', models.TextField()),
                ('REQUESTER_NAME', models.TextField()),
                ('CATEGORY_TYPE', models.TextField()),
                ('CEO_PHONE', models.TextField()),
            ],
            options={
                'db_table': 'AS_REQUESTS',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
            ],
            options={
                'db_table': 'MSA_RESPONSES',
            },
        ),
        migrations.CreateModel(
            name='Response_activites',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.TextField()),
                ('activity_code', models.TextField()),
                ('activity_title', models.TextField()),
                ('activity_description', models.TextField()),
                ('notification_type', models.TextField()),
                ('creation_date', models.DateField()),
                ('created_by', models.TextField()),
            ],
            options={
                'db_table': 'msa_response_activites',
            },
        ),
        migrations.CreateModel(
            name='Response_attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.TextField()),
                ('attachment_type_id', models.TextField()),
                ('attachment_display_name', models.TextField()),
                ('attachment_file_path', models.FileField(upload_to=printPreview.models.get_upload_to)),
                ('creation_date', models.DateField()),
                ('created_by', models.TextField()),
                ('response_id', models.IntegerField()),
            ],
            options={
                'db_table': 'msa_response_attachments',
            },
        ),
        migrations.CreateModel(
            name='Response_external_entites',
            fields=[
                ('external_entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_external_entity_id', models.IntegerField()),
                ('comments', models.TextField()),
                ('creation_date', models.DateField()),
                ('created_by', models.TextField()),
                ('DESCISION_ID', models.TextField()),
                ('response_id', models.IntegerField()),
            ],
            options={
                'db_table': 'msa_response_external_entities',
            },
        ),
        migrations.CreateModel(
            name='Request_Attachements',
            fields=[
                ('ATTACHMENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('attachment_display_name', models.TextField()),
                ('attachment_file_path', models.TextField()),
                ('attachment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printPreview.attachements_type')),
            ],
            options={
                'db_table': 'msa_request_attachments',
            },
        ),
    ]
