# Generated by Django 4.0.4 on 2023-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printPreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_Entity',
            fields=[
                ('external_entity_no', models.IntegerField(primary_key=True, serialize=False)),
                ('external_entity_name', models.IntegerField()),
                ('request_id', models.IntegerField()),
            ],
            options={
                'db_table': 'external_entity_view',
            },
        ),
    ]
